name: Build Latest Release of Chia & Chia Dev Tools

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: "latest"
  cancel-in-progress: true

jobs:
  docker_build_and_publish_github:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGE_ADMIN_PAT }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}

      # Get the most recent release from chia-blockchain and build that
      - uses: actions/github-script@v6
        id: 'latest-tag'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            const release = await github.rest.repos.getLatestRelease({
              owner: 'Chia-Network',
              repo: 'chia-blockchain',
            });
            return release.data.tag_name;

      # Get the most recent release from chia-dev-tools and build that
      - uses: actions/github-script@v6
        id: 'cdv-latest-tag'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            const release = await github.rest.repos.getLatestRelease({
              owner: 'Chia-Network',
              repo: 'chia-dev-tools',
            });
            return release.data.tag_name;

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/chia-network/chia-simulator
            chianetwork/chia-simulator-docker
          labels: |
            org.opencontainers.image.title=One-Click Chia Simulator
            org.opencontainers.image.vendor=Chia Network
          tags: |
            type=raw,value=latest
            type=raw,value=${{ steps.latest-tag.outputs.result }}
            type=raw,value=${{ steps.cdv-latest-tag.outputs.result }}

      - name: Build docker image and push to github packages
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          no-cache: true
          push: true
          build-args: |
            "CHIA_BRANCH=${{ steps.latest-tag.outputs.result }}"
            "DEV_TOOLS_BRANCH=${{ steps.cdv-latest-tag.outputs.result }}"
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
